apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: demoapp
      tier: frontend
  template:
    metadata:
      labels:
        app: demoapp
        tier: frontend
    spec:
      containers:
      - name: demoapp
        image: dockerhamse/demoapp:22
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
